/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class AccountResponseBuilder {
    //the instance to build
    private AccountResponse accountResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AccountResponseBuilder() {
        accountResponse = new AccountResponse();
    }

    public AccountResponseBuilder usage(Usage usage) {
        accountResponse.setUsage(usage);
        return this;
    }

    /**
     * The user identifier.
     */
    public AccountResponseBuilder id(String id) {
        accountResponse.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AccountResponse build() {
        return accountResponse;
    }
}