/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AccountResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4942463617738068004L;
    private Usage usage;
    private String id;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("usage")
    public Usage getUsage ( ) { 
        return this.usage;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("usage")
    public void setUsage (Usage value) { 
        this.usage = value;
    }
 
    /** GETTER
     * The user identifier.
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * The user identifier.
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
}
 