/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class BaseFolderMetadataBuilder {
    //the instance to build
    private BaseFolderMetadata baseFolderMetadata;

    /**
     * Default constructor to initialize the instance
     */
    public BaseFolderMetadataBuilder() {
        baseFolderMetadata = new BaseFolderMetadata();
    }

    /**
     * The name of the folder
     */
    public BaseFolderMetadataBuilder name(String name) {
        baseFolderMetadata.setName(name);
        return this;
    }

    /**
     * The name of the folder's parent folder
     */
    public BaseFolderMetadataBuilder parentPath(String parentPath) {
        baseFolderMetadata.setParentPath(parentPath);
        return this;
    }

    /**
     * The size of the folder, in bytes
     */
    public BaseFolderMetadataBuilder size(long size) {
        baseFolderMetadata.setSize(size);
        return this;
    }

    /**
     * Folder version.  This number increases when the folder content changes
     */
    public BaseFolderMetadataBuilder version(int version) {
        baseFolderMetadata.setVersion(version);
        return this;
    }

    /**
     * Creation timestamp for the folder's current version, in ISO-8601 format
     */
    public BaseFolderMetadataBuilder versionCreated(String versionCreated) {
        baseFolderMetadata.setVersionCreated(versionCreated);
        return this;
    }

    /**
     * The number of items the folder contains
     */
    public BaseFolderMetadataBuilder count(int count) {
        baseFolderMetadata.setCount(count);
        return this;
    }

    /**
     * If true, the folder has been logically deleted
     */
    public BaseFolderMetadataBuilder deleted(boolean deleted) {
        baseFolderMetadata.setDeleted(deleted);
        return this;
    }

    /**
     * Array of viewUid
     */
    public BaseFolderMetadataBuilder viewUid(List<ViewUid> viewUid) {
        baseFolderMetadata.setViewUid(viewUid);
        return this;
    }

    /**
     * Unique identifier of the resource
     */
    public BaseFolderMetadataBuilder uri(String uri) {
        baseFolderMetadata.setUri(uri);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BaseFolderMetadata build() {
        return baseFolderMetadata;
    }
}