/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class BaseFileMetadataBuilder {
    //the instance to build
    private BaseFileMetadata baseFileMetadata;

    /**
     * Default constructor to initialize the instance
     */
    public BaseFileMetadataBuilder() {
        baseFileMetadata = new BaseFileMetadata();
    }

    /**
     * The name of the file
     */
    public BaseFileMetadataBuilder name(String name) {
        baseFileMetadata.setName(name);
        return this;
    }

    /**
     * The folder where the file is located
     */
    public BaseFileMetadataBuilder parentPath(String parentPath) {
        baseFileMetadata.setParentPath(parentPath);
        return this;
    }

    /**
     * The file content's SHA-256 checksum value
     */
    public BaseFileMetadataBuilder checksum(String checksum) {
        baseFileMetadata.setChecksum(checksum);
        return this;
    }

    /**
     * If false, the file content is protected by copywrite and is not accessible to the user
     */
    public BaseFileMetadataBuilder contentAccessible(boolean contentAccessible) {
        baseFileMetadata.setContentAccessible(contentAccessible);
        return this;
    }

    /**
     * A unique string representing the file. Will change if file content is updated.  Required for certain APIs, such as /thumbnails
     */
    public BaseFileMetadataBuilder contentToken(String contentToken) {
        baseFileMetadata.setContentToken(contentToken);
        return this;
    }

    /**
     * If true, the file has been logically deleted
     */
    public BaseFileMetadataBuilder deleted(boolean deleted) {
        baseFileMetadata.setDeleted(deleted);
        return this;
    }

    /**
     * The file's extension, as extracted from the filename
     */
    public BaseFileMetadataBuilder extension(String extension) {
        baseFileMetadata.setExtension(extension);
        return this;
    }

    /**
     * The size of the file, in bytes
     */
    public BaseFileMetadataBuilder size(long size) {
        baseFileMetadata.setSize(size);
        return this;
    }

    /**
     * A set of file attributes.  The attribute set will vary depending on file type
     */
    public BaseFileMetadataBuilder systemAttributes(Object systemAttributes) {
        baseFileMetadata.setSystemAttributes(systemAttributes);
        return this;
    }

    /**
     * File version.  This number increases when the file is updated
     */
    public BaseFileMetadataBuilder version(int version) {
        baseFileMetadata.setVersion(version);
        return this;
    }

    /**
     * Creation timestamp for the file's current version, in ISO-8601 format
     */
    public BaseFileMetadataBuilder versionCreated(String versionCreated) {
        baseFileMetadata.setVersionCreated(versionCreated);
        return this;
    }

    /**
     * Array of viewUid
     */
    public BaseFileMetadataBuilder viewUid(List<ViewUid> viewUid) {
        baseFileMetadata.setViewUid(viewUid);
        return this;
    }

    /**
     * Unique identifier of the resource
     */
    public BaseFileMetadataBuilder uri(String uri) {
        baseFileMetadata.setUri(uri);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BaseFileMetadata build() {
        return baseFileMetadata;
    }
}