/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ContactsAddrbookBuilder {
    //the instance to build
    private ContactsAddrbook contactsAddrbook;

    /**
     * Default constructor to initialize the instance
     */
    public ContactsAddrbookBuilder() {
        contactsAddrbook = new ContactsAddrbook();
    }

    /**
     * Timestamp of latest update
     */
    public ContactsAddrbookBuilder updated(String updated) {
        contactsAddrbook.setUpdated(updated);
        return this;
    }

    public ContactsAddrbookBuilder contacts(ContactsContacts contacts) {
        contactsAddrbook.setContacts(contacts);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ContactsAddrbook build() {
        return contactsAddrbook;
    }
}