/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ContactsAddressBuilder {
    //the instance to build
    private ContactsAddress contactsAddress;

    /**
     * Default constructor to initialize the instance
     */
    public ContactsAddressBuilder() {
        contactsAddress = new ContactsAddress();
    }

    /**
     * Type of address, e.g. home, business, etc
     */
    public ContactsAddressBuilder type(String type) {
        contactsAddress.setType(type);
        return this;
    }

    /**
     * When combined with 'type', provides a unique identifier for the entry
     */
    public ContactsAddressBuilder indx(int indx) {
        contactsAddress.setIndx(indx);
        return this;
    }

    /**
     * For sorting. Lower numbers indicate a higher preference
     */
    public ContactsAddressBuilder preference(String preference) {
        contactsAddress.setPreference(preference);
        return this;
    }

    public ContactsAddressBuilder pobox(String pobox) {
        contactsAddress.setPobox(pobox);
        return this;
    }

    public ContactsAddressBuilder street(String street) {
        contactsAddress.setStreet(street);
        return this;
    }

    public ContactsAddressBuilder city(String city) {
        contactsAddress.setCity(city);
        return this;
    }

    public ContactsAddressBuilder zipcode(String zipcode) {
        contactsAddress.setZipcode(zipcode);
        return this;
    }

    public ContactsAddressBuilder country(String country) {
        contactsAddress.setCountry(country);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ContactsAddress build() {
        return contactsAddress;
    }
}