/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ContactsImBuilder {
    //the instance to build
    private ContactsIm contactsIm;

    /**
     * Default constructor to initialize the instance
     */
    public ContactsImBuilder() {
        contactsIm = new ContactsIm();
    }

    /**
     * Type of address, e.g. home, business, etc
     */
    public ContactsImBuilder type(String type) {
        contactsIm.setType(type);
        return this;
    }

    /**
     * IM contact string
     */
    public ContactsImBuilder address(String address) {
        contactsIm.setAddress(address);
        return this;
    }

    /**
     * For sorting. Lower numbers indicate a higher preference
     */
    public ContactsImBuilder preference(String preference) {
        contactsIm.setPreference(preference);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ContactsIm build() {
        return contactsIm;
    }
}