/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ContactsAccountBuilder {
    //the instance to build
    private ContactsAccount contactsAccount;

    /**
     * Default constructor to initialize the instance
     */
    public ContactsAccountBuilder() {
        contactsAccount = new ContactsAccount();
    }

    /**
     * Unique identifier for the current user
     */
    public ContactsAccountBuilder userid(String userid) {
        contactsAccount.setUserid(userid);
        return this;
    }

    public ContactsAccountBuilder addrbook(ContactsAddrbook addrbook) {
        contactsAccount.setAddrbook(addrbook);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ContactsAccount build() {
        return contactsAccount;
    }
}