/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ContactsEmailBuilder {
    //the instance to build
    private ContactsEmail contactsEmail;

    /**
     * Default constructor to initialize the instance
     */
    public ContactsEmailBuilder() {
        contactsEmail = new ContactsEmail();
    }

    /**
     * Type of email address, e.g. personal, business, etc
     */
    public ContactsEmailBuilder type(String type) {
        contactsEmail.setType(type);
        return this;
    }

    /**
     * When combined with 'type', provides a unique identifier for the entry
     */
    public ContactsEmailBuilder indx(int indx) {
        contactsEmail.setIndx(indx);
        return this;
    }

    /**
     * Email address
     */
    public ContactsEmailBuilder address(String address) {
        contactsEmail.setAddress(address);
        return this;
    }

    /**
     * For sorting. Lower numbers indicate a higher preference
     */
    public ContactsEmailBuilder preference(String preference) {
        contactsEmail.setPreference(preference);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ContactsEmail build() {
        return contactsEmail;
    }
}