/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ContactsTelBuilder {
    //the instance to build
    private ContactsTel contactsTel;

    /**
     * Default constructor to initialize the instance
     */
    public ContactsTelBuilder() {
        contactsTel = new ContactsTel();
    }

    /**
     * Type of telephone number, e.g. home, mobile, etc
     */
    public ContactsTelBuilder type(String type) {
        contactsTel.setType(type);
        return this;
    }

    /**
     * When combined with 'type', provides a unique identifier for the entry
     */
    public ContactsTelBuilder indx(int indx) {
        contactsTel.setIndx(indx);
        return this;
    }

    /**
     * Telephone number
     */
    public ContactsTelBuilder number(String number) {
        contactsTel.setNumber(number);
        return this;
    }

    /**
     * When sorting, lower numbers indicate a higher preference
     */
    public ContactsTelBuilder preference(String preference) {
        contactsTel.setPreference(preference);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ContactsTel build() {
        return contactsTel;
    }
}