/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ContactsResponseBuilder {
    //the instance to build
    private ContactsResponse contactsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ContactsResponseBuilder() {
        contactsResponse = new ContactsResponse();
    }

    public ContactsResponseBuilder account(ContactsAccount account) {
        contactsResponse.setAccount(account);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ContactsResponse build() {
        return contactsResponse;
    }
}