/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ContactsResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5756431222426063474L;
    private ContactsAccount account;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("account")
    public ContactsAccount getAccount ( ) { 
        return this.account;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("account")
    public void setAccount (ContactsAccount value) { 
        this.account = value;
    }
 
}
 