/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Contacts 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4784732520912312555L;
    private ContactsResponse contactsResponse;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("contactsResponse")
    public ContactsResponse getContactsResponse ( ) { 
        return this.contactsResponse;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("contactsResponse")
    public void setContactsResponse (ContactsResponse value) { 
        this.contactsResponse = value;
    }
 
}
 