/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ContactsEmail 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5537529800373785359L;
    private String type;
    private int indx;
    private String address;
    private String preference;
    /** GETTER
     * Type of email address, e.g. personal, business, etc
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Type of email address, e.g. personal, business, etc
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * When combined with 'type', provides a unique identifier for the entry
     */
    @JsonGetter("indx")
    public int getIndx ( ) { 
        return this.indx;
    }
    
    /** SETTER
     * When combined with 'type', provides a unique identifier for the entry
     */
    @JsonSetter("indx")
    public void setIndx (int value) { 
        this.indx = value;
    }
 
    /** GETTER
     * Email address
     */
    @JsonGetter("address")
    public String getAddress ( ) { 
        return this.address;
    }
    
    /** SETTER
     * Email address
     */
    @JsonSetter("address")
    public void setAddress (String value) { 
        this.address = value;
    }
 
    /** GETTER
     * For sorting. Lower numbers indicate a higher preference
     */
    @JsonGetter("preference")
    public String getPreference ( ) { 
        return this.preference;
    }
    
    /** SETTER
     * For sorting. Lower numbers indicate a higher preference
     */
    @JsonSetter("preference")
    public void setPreference (String value) { 
        this.preference = value;
    }
 
}
 