/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ContactsBuilder {
    //the instance to build
    private Contacts contacts;

    /**
     * Default constructor to initialize the instance
     */
    public ContactsBuilder() {
        contacts = new Contacts();
    }

    public ContactsBuilder contactsResponse(ContactsResponse contactsResponse) {
        contacts.setContactsResponse(contactsResponse);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Contacts build() {
        return contacts;
    }
}