/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ContactsContacts 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4742109213680157375L;
    private int itemcount;
    private List<Contact> contact;
    /** GETTER
     * Number of contacts
     */
    @JsonGetter("itemcount")
    public int getItemcount ( ) { 
        return this.itemcount;
    }
    
    /** SETTER
     * Number of contacts
     */
    @JsonSetter("itemcount")
    public void setItemcount (int value) { 
        this.itemcount = value;
    }
 
    /** GETTER
     * Array of contacts
     */
    @JsonGetter("contact")
    public List<Contact> getContact ( ) { 
        return this.contact;
    }
    
    /** SETTER
     * Array of contacts
     */
    @JsonSetter("contact")
    public void setContact (List<Contact> value) { 
        this.contact = value;
    }
 
}
 