/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ContactsContactsBuilder {
    //the instance to build
    private ContactsContacts contactsContacts;

    /**
     * Default constructor to initialize the instance
     */
    public ContactsContactsBuilder() {
        contactsContacts = new ContactsContacts();
    }

    /**
     * Number of contacts
     */
    public ContactsContactsBuilder itemcount(int itemcount) {
        contactsContacts.setItemcount(itemcount);
        return this;
    }

    /**
     * Array of contacts
     */
    public ContactsContactsBuilder contact(List<Contact> contact) {
        contactsContacts.setContact(contact);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ContactsContacts build() {
        return contactsContacts;
    }
}