/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ContactsIm 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5277836127919725213L;
    private String type;
    private String address;
    private String preference;
    /** GETTER
     * Type of address, e.g. home, business, etc
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Type of address, e.g. home, business, etc
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * IM contact string
     */
    @JsonGetter("address")
    public String getAddress ( ) { 
        return this.address;
    }
    
    /** SETTER
     * IM contact string
     */
    @JsonSetter("address")
    public void setAddress (String value) { 
        this.address = value;
    }
 
    /** GETTER
     * For sorting. Lower numbers indicate a higher preference
     */
    @JsonGetter("preference")
    public String getPreference ( ) { 
        return this.preference;
    }
    
    /** SETTER
     * For sorting. Lower numbers indicate a higher preference
     */
    @JsonSetter("preference")
    public void setPreference (String value) { 
        this.preference = value;
    }
 
}
 