/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ContactsAccount 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5406826769553189386L;
    private String userid;
    private ContactsAddrbook addrbook;
    /** GETTER
     * Unique identifier for the current user
     */
    @JsonGetter("userid")
    public String getUserid ( ) { 
        return this.userid;
    }
    
    /** SETTER
     * Unique identifier for the current user
     */
    @JsonSetter("userid")
    public void setUserid (String value) { 
        this.userid = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("addrbook")
    public ContactsAddrbook getAddrbook ( ) { 
        return this.addrbook;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("addrbook")
    public void setAddrbook (ContactsAddrbook value) { 
        this.addrbook = value;
    }
 
}
 