/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ContactsAddrbook 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5500815484472302225L;
    private String updated;
    private ContactsContacts contacts;
    /** GETTER
     * Timestamp of latest update
     */
    @JsonGetter("updated")
    public String getUpdated ( ) { 
        return this.updated;
    }
    
    /** SETTER
     * Timestamp of latest update
     */
    @JsonSetter("updated")
    public void setUpdated (String value) { 
        this.updated = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("contacts")
    public ContactsContacts getContacts ( ) { 
        return this.contacts;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("contacts")
    public void setContacts (ContactsContacts value) { 
        this.contacts = value;
    }
 
}
 