/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ContactsTel 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5538348768314112547L;
    private String type;
    private int indx;
    private String number;
    private String preference;
    /** GETTER
     * Type of telephone number, e.g. home, mobile, etc
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Type of telephone number, e.g. home, mobile, etc
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * When combined with 'type', provides a unique identifier for the entry
     */
    @JsonGetter("indx")
    public int getIndx ( ) { 
        return this.indx;
    }
    
    /** SETTER
     * When combined with 'type', provides a unique identifier for the entry
     */
    @JsonSetter("indx")
    public void setIndx (int value) { 
        this.indx = value;
    }
 
    /** GETTER
     * Telephone number
     */
    @JsonGetter("number")
    public String getNumber ( ) { 
        return this.number;
    }
    
    /** SETTER
     * Telephone number
     */
    @JsonSetter("number")
    public void setNumber (String value) { 
        this.number = value;
    }
 
    /** GETTER
     * When sorting, lower numbers indicate a higher preference
     */
    @JsonGetter("preference")
    public String getPreference ( ) { 
        return this.preference;
    }
    
    /** SETTER
     * When sorting, lower numbers indicate a higher preference
     */
    @JsonSetter("preference")
    public void setPreference (String value) { 
        this.preference = value;
    }
 
}
 