/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ContactsAddress 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5592181820836467204L;
    private String type;
    private int indx;
    private String preference;
    private String pobox;
    private String street;
    private String city;
    private String zipcode;
    private String country;
    /** GETTER
     * Type of address, e.g. home, business, etc
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Type of address, e.g. home, business, etc
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * When combined with 'type', provides a unique identifier for the entry
     */
    @JsonGetter("indx")
    public int getIndx ( ) { 
        return this.indx;
    }
    
    /** SETTER
     * When combined with 'type', provides a unique identifier for the entry
     */
    @JsonSetter("indx")
    public void setIndx (int value) { 
        this.indx = value;
    }
 
    /** GETTER
     * For sorting. Lower numbers indicate a higher preference
     */
    @JsonGetter("preference")
    public String getPreference ( ) { 
        return this.preference;
    }
    
    /** SETTER
     * For sorting. Lower numbers indicate a higher preference
     */
    @JsonSetter("preference")
    public void setPreference (String value) { 
        this.preference = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("pobox")
    public String getPobox ( ) { 
        return this.pobox;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("pobox")
    public void setPobox (String value) { 
        this.pobox = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("street")
    public String getStreet ( ) { 
        return this.street;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("street")
    public void setStreet (String value) { 
        this.street = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("city")
    public String getCity ( ) { 
        return this.city;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("city")
    public void setCity (String value) { 
        this.city = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("zipcode")
    public String getZipcode ( ) { 
        return this.zipcode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("zipcode")
    public void setZipcode (String value) { 
        this.zipcode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("country")
    public String getCountry ( ) { 
        return this.country;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("country")
    public void setCountry (String value) { 
        this.country = value;
    }
 
}
 