/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class CreateShareRequestBuilder {
    //the instance to build
    private CreateShareRequest createShareRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateShareRequestBuilder() {
        createShareRequest = new CreateShareRequest();
    }

    /**
     * An array of resource request object.
     */
    public CreateShareRequestBuilder resources(List<ResourceRequest> resources) {
        createShareRequest.setResources(resources);
        return this;
    }

    /**
     * The name of the share.
     */
    public CreateShareRequestBuilder name(String name) {
        createShareRequest.setName(name);
        return this;
    }

    /**
     * The time to live of the share in seconds. The value 0 signifies the share will never expire. Minimum value is 300. If not provided, defaults to 86400.
     */
    public CreateShareRequestBuilder expiresIn(Integer expiresIn) {
        createShareRequest.setExpiresIn(expiresIn);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateShareRequest build() {
        return createShareRequest;
    }
}