/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreateShareRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5760479291804540125L;
    private List<ResourceRequest> resources;
    private String name;
    private Integer expiresIn;
    /** GETTER
     * An array of resource request object.
     */
    @JsonGetter("resources")
    public List<ResourceRequest> getResources ( ) { 
        return this.resources;
    }
    
    /** SETTER
     * An array of resource request object.
     */
    @JsonSetter("resources")
    public void setResources (List<ResourceRequest> value) { 
        this.resources = value;
    }
 
    /** GETTER
     * The name of the share.
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * The name of the share.
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * The time to live of the share in seconds. The value 0 signifies the share will never expire. Minimum value is 300. If not provided, defaults to 86400.
     */
    @JsonGetter("expiresIn")
    public Integer getExpiresIn ( ) { 
        return this.expiresIn;
    }
    
    /** SETTER
     * The time to live of the share in seconds. The value 0 signifies the share will never expire. Minimum value is 300. If not provided, defaults to 86400.
     */
    @JsonSetter("expiresIn")
    public void setExpiresIn (Integer value) { 
        this.expiresIn = value;
    }
 
}
 