/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class CreateShareResponseBuilder {
    //the instance to build
    private CreateShareResponse createShareResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CreateShareResponseBuilder() {
        createShareResponse = new CreateShareResponse();
    }

    /**
     * The name of the share.
     */
    public CreateShareResponseBuilder name(String name) {
        createShareResponse.setName(name);
        return this;
    }

    public CreateShareResponseBuilder links(List<LinkResponse> links) {
        createShareResponse.setLinks(links);
        return this;
    }

    /**
     * The resource identifier.
     */
    public CreateShareResponseBuilder uid(String uid) {
        createShareResponse.setUid(uid);
        return this;
    }

    /**
     * The owner of the share
     */
    public CreateShareResponseBuilder owner(Object owner) {
        createShareResponse.setOwner(owner);
        return this;
    }

    /**
     * The sharer of the share
     */
    public CreateShareResponseBuilder sharer(Object sharer) {
        createShareResponse.setSharer(sharer);
        return this;
    }

    /**
     * The total count of shared resources.
     */
    public CreateShareResponseBuilder totalResourceCount(Integer totalResourceCount) {
        createShareResponse.setTotalResourceCount(totalResourceCount);
        return this;
    }

    /**
     * The time to live of the share in seconds.
     */
    public CreateShareResponseBuilder expiresIn(Integer expiresIn) {
        createShareResponse.setExpiresIn(expiresIn);
        return this;
    }

    /**
     * Expiration date on the share.
     */
    public CreateShareResponseBuilder expirationDate(String expirationDate) {
        createShareResponse.setExpirationDate(expirationDate);
        return this;
    }

    /**
     * The date and time the share was created.
     */
    public CreateShareResponseBuilder creationDate(String creationDate) {
        createShareResponse.setCreationDate(creationDate);
        return this;
    }

    /**
     * The date and time the share was last modified from the perspective of the owner.
     */
    public CreateShareResponseBuilder lastModifiedDate(String lastModifiedDate) {
        createShareResponse.setLastModifiedDate(lastModifiedDate);
        return this;
    }

    /**
     * The date and time the share was last modified from the perspective of a member.
     */
    public CreateShareResponseBuilder inboundLastModifiedDate(String inboundLastModifiedDate) {
        createShareResponse.setInboundLastModifiedDate(inboundLastModifiedDate);
        return this;
    }

    /**
     * The invite key of a public share.
     */
    public CreateShareResponseBuilder publicInviteKey(String publicInviteKey) {
        createShareResponse.setPublicInviteKey(publicInviteKey);
        return this;
    }

    /**
     * Array of resources
     */
    public CreateShareResponseBuilder resources(List<ResourceResponse> resources) {
        createShareResponse.setResources(resources);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateShareResponse build() {
        return createShareResponse;
    }
}