/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class DeletedListBuilder {
    //the instance to build
    private DeletedList deletedList;

    /**
     * Default constructor to initialize the instance
     */
    public DeletedListBuilder() {
        deletedList = new DeletedList();
    }

    /**
     * An array of deleted file and folder paths.
     */
    public DeletedListBuilder path(List<String> path) {
        deletedList.setPath(path);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeletedList build() {
        return deletedList;
    }
}