/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeletedList 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5054022887426813727L;
    private List<String> path;
    /** GETTER
     * An array of deleted file and folder paths.
     */
    @JsonGetter("path")
    public List<String> getPath ( ) { 
        return this.path;
    }
    
    /** SETTER
     * An array of deleted file and folder paths.
     */
    @JsonSetter("path")
    public void setPath (List<String> value) { 
        this.path = value;
    }
 
}
 