/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class FileMetadataBuilder {
    //the instance to build
    private FileMetadata fileMetadata;

    /**
     * Default constructor to initialize the instance
     */
    public FileMetadataBuilder() {
        fileMetadata = new FileMetadata();
    }

    /**
     * The name of the file
     */
    public FileMetadataBuilder name(String name) {
        fileMetadata.setName(name);
        return this;
    }

    /**
     * The folder where the file is located
     */
    public FileMetadataBuilder parentPath(String parentPath) {
        fileMetadata.setParentPath(parentPath);
        return this;
    }

    /**
     * The file content's SHA-256 checksum value
     */
    public FileMetadataBuilder checksum(String checksum) {
        fileMetadata.setChecksum(checksum);
        return this;
    }

    /**
     * If false, the file content is protected by copywrite and is not accessible to the user
     */
    public FileMetadataBuilder contentAccessible(boolean contentAccessible) {
        fileMetadata.setContentAccessible(contentAccessible);
        return this;
    }

    /**
     * A unique string representing the file. Will change if file content is updated.  Required for certain APIs, such as /thumbnails
     */
    public FileMetadataBuilder contentToken(String contentToken) {
        fileMetadata.setContentToken(contentToken);
        return this;
    }

    /**
     * If true, the file has been logically deleted
     */
    public FileMetadataBuilder deleted(boolean deleted) {
        fileMetadata.setDeleted(deleted);
        return this;
    }

    /**
     * The file's extension, as extracted from the filename
     */
    public FileMetadataBuilder extension(String extension) {
        fileMetadata.setExtension(extension);
        return this;
    }

    /**
     * The size of the file, in bytes
     */
    public FileMetadataBuilder size(long size) {
        fileMetadata.setSize(size);
        return this;
    }

    /**
     * A set of file attributes.  The attribute set will vary depending on file type
     */
    public FileMetadataBuilder systemAttributes(Object systemAttributes) {
        fileMetadata.setSystemAttributes(systemAttributes);
        return this;
    }

    /**
     * File version.  This number increases when the file is updated
     */
    public FileMetadataBuilder version(int version) {
        fileMetadata.setVersion(version);
        return this;
    }

    /**
     * Creation timestamp for the file's current version, in ISO-8601 format
     */
    public FileMetadataBuilder versionCreated(String versionCreated) {
        fileMetadata.setVersionCreated(versionCreated);
        return this;
    }

    /**
     * Array of viewUid
     */
    public FileMetadataBuilder viewUid(List<ViewUid> viewUid) {
        fileMetadata.setViewUid(viewUid);
        return this;
    }

    /**
     * Unique identifier of the resource
     */
    public FileMetadataBuilder uri(String uri) {
        fileMetadata.setUri(uri);
        return this;
    }

    /**
     * Array of shareAssociation
     */
    public FileMetadataBuilder shareAssociation(List<ShareAssociation> shareAssociation) {
        fileMetadata.setShareAssociation(shareAssociation);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FileMetadata build() {
        return fileMetadata;
    }
}