/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class FolderRequestBuilder {
    //the instance to build
    private FolderRequest folderRequest;

    /**
     * Default constructor to initialize the instance
     */
    public FolderRequestBuilder() {
        folderRequest = new FolderRequest();
    }

    /**
     * Folder name to be created.
     */
    public FolderRequestBuilder name(String name) {
        folderRequest.setName(name);
        return this;
    }

    /**
     * Path where the folder has to be created.
     */
    public FolderRequestBuilder path(String path) {
        folderRequest.setPath(path);
        return this;
    }

    /**
     * Specifies what happens if a folder of the same name exists at the target path. Set to 'overwrite' to overwrite the existing folder. Set to 'modify' to treat the new folder as a modification of the old folder. If the 'override' parameter is not set, the following algorithm is applied if the existing folder has a 'deleted' attribute set to 'true', the folder is overwritten; if the old folder's 'deleted' attribute is false or not set, the folder is modified.
     */
    public FolderRequestBuilder override(String override) {
        folderRequest.setOverride(override);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FolderRequest build() {
        return folderRequest;
    }
}