/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class FolderMetadata 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5223501996650117994L;
    private String name;
    private String parentPath;
    private long size;
    private int version;
    private String versionCreated;
    private int count;
    private boolean deleted;
    private List<ViewUid> viewUid;
    private String uri;
    private List<ShareAssociation> shareAssociation;
    /** GETTER
     * The name of the folder
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * The name of the folder
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * The name of the folder's parent folder
     */
    @JsonGetter("parentPath")
    public String getParentPath ( ) { 
        return this.parentPath;
    }
    
    /** SETTER
     * The name of the folder's parent folder
     */
    @JsonSetter("parentPath")
    public void setParentPath (String value) { 
        this.parentPath = value;
    }
 
    /** GETTER
     * The size of the folder, in bytes
     */
    @JsonGetter("size")
    public long getSize ( ) { 
        return this.size;
    }
    
    /** SETTER
     * The size of the folder, in bytes
     */
    @JsonSetter("size")
    public void setSize (long value) { 
        this.size = value;
    }
 
    /** GETTER
     * Folder version.  This number increases when the folder content changes
     */
    @JsonGetter("version")
    public int getVersion ( ) { 
        return this.version;
    }
    
    /** SETTER
     * Folder version.  This number increases when the folder content changes
     */
    @JsonSetter("version")
    public void setVersion (int value) { 
        this.version = value;
    }
 
    /** GETTER
     * Creation timestamp for the folder's current version, in ISO-8601 format
     */
    @JsonGetter("versionCreated")
    public String getVersionCreated ( ) { 
        return this.versionCreated;
    }
    
    /** SETTER
     * Creation timestamp for the folder's current version, in ISO-8601 format
     */
    @JsonSetter("versionCreated")
    public void setVersionCreated (String value) { 
        this.versionCreated = value;
    }
 
    /** GETTER
     * The number of items the folder contains
     */
    @JsonGetter("count")
    public int getCount ( ) { 
        return this.count;
    }
    
    /** SETTER
     * The number of items the folder contains
     */
    @JsonSetter("count")
    public void setCount (int value) { 
        this.count = value;
    }
 
    /** GETTER
     * If true, the folder has been logically deleted
     */
    @JsonGetter("deleted")
    public boolean getDeleted ( ) { 
        return this.deleted;
    }
    
    /** SETTER
     * If true, the folder has been logically deleted
     */
    @JsonSetter("deleted")
    public void setDeleted (boolean value) { 
        this.deleted = value;
    }
 
    /** GETTER
     * Array of viewUid
     */
    @JsonGetter("viewUid")
    public List<ViewUid> getViewUid ( ) { 
        return this.viewUid;
    }
    
    /** SETTER
     * Array of viewUid
     */
    @JsonSetter("viewUid")
    public void setViewUid (List<ViewUid> value) { 
        this.viewUid = value;
    }
 
    /** GETTER
     * Unique identifier of the resource
     */
    @JsonGetter("uri")
    public String getUri ( ) { 
        return this.uri;
    }
    
    /** SETTER
     * Unique identifier of the resource
     */
    @JsonSetter("uri")
    public void setUri (String value) { 
        this.uri = value;
    }
 
    /** GETTER
     * Array of shareAssociation
     */
    @JsonGetter("shareAssociation")
    public List<ShareAssociation> getShareAssociation ( ) { 
        return this.shareAssociation;
    }
    
    /** SETTER
     * Array of shareAssociation
     */
    @JsonSetter("shareAssociation")
    public void setShareAssociation (List<ShareAssociation> value) { 
        this.shareAssociation = value;
    }
 
}
 