/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class FolderMetadataBuilder {
    //the instance to build
    private FolderMetadata folderMetadata;

    /**
     * Default constructor to initialize the instance
     */
    public FolderMetadataBuilder() {
        folderMetadata = new FolderMetadata();
    }

    /**
     * The name of the folder
     */
    public FolderMetadataBuilder name(String name) {
        folderMetadata.setName(name);
        return this;
    }

    /**
     * The name of the folder's parent folder
     */
    public FolderMetadataBuilder parentPath(String parentPath) {
        folderMetadata.setParentPath(parentPath);
        return this;
    }

    /**
     * The size of the folder, in bytes
     */
    public FolderMetadataBuilder size(long size) {
        folderMetadata.setSize(size);
        return this;
    }

    /**
     * Folder version.  This number increases when the folder content changes
     */
    public FolderMetadataBuilder version(int version) {
        folderMetadata.setVersion(version);
        return this;
    }

    /**
     * Creation timestamp for the folder's current version, in ISO-8601 format
     */
    public FolderMetadataBuilder versionCreated(String versionCreated) {
        folderMetadata.setVersionCreated(versionCreated);
        return this;
    }

    /**
     * The number of items the folder contains
     */
    public FolderMetadataBuilder count(int count) {
        folderMetadata.setCount(count);
        return this;
    }

    /**
     * If true, the folder has been logically deleted
     */
    public FolderMetadataBuilder deleted(boolean deleted) {
        folderMetadata.setDeleted(deleted);
        return this;
    }

    /**
     * Array of viewUid
     */
    public FolderMetadataBuilder viewUid(List<ViewUid> viewUid) {
        folderMetadata.setViewUid(viewUid);
        return this;
    }

    /**
     * Unique identifier of the resource
     */
    public FolderMetadataBuilder uri(String uri) {
        folderMetadata.setUri(uri);
        return this;
    }

    /**
     * Array of shareAssociation
     */
    public FolderMetadataBuilder shareAssociation(List<ShareAssociation> shareAssociation) {
        folderMetadata.setShareAssociation(shareAssociation);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FolderMetadata build() {
        return folderMetadata;
    }
}