/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class FopsChangeRequestBuilder {
    //the instance to build
    private FopsChangeRequest fopsChangeRequest;

    /**
     * Default constructor to initialize the instance
     */
    public FopsChangeRequestBuilder() {
        fopsChangeRequest = new FopsChangeRequest();
    }

    /**
     * Full path of the file/folder for copy/move/rename operations.
     */
    public FopsChangeRequestBuilder src(String src) {
        fopsChangeRequest.setSrc(src);
        return this;
    }

    /**
     * Full path of the target file/folder for copy/move/rename operations. In case of files the full/changed name should be included in the target.
     */
    public FopsChangeRequestBuilder target(String target) {
        fopsChangeRequest.setTarget(target);
        return this;
    }

    /**
     * If 'true', ensures that name conflicts are resolved according to the value of the 'conflictsolve' parameter. Defaults to 'false', in which case the operation will overwrite an existing file/folder of the same name.
     */
    public FopsChangeRequestBuilder safe(boolean safe) {
        fopsChangeRequest.setSafe(safe);
        return this;
    }

    /**
     * Defines how name conflicts are resolved, if the 'safe' parameter is set to 'true'. If set to 'copy', a new file is written to the destination folder with a non-conflicting name. If not set, the operation is rolled back and operation returns '409 Conflict'.
     */
    public FopsChangeRequestBuilder conflictsolve(String conflictsolve) {
        fopsChangeRequest.setConflictsolve(conflictsolve);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FopsChangeRequest build() {
        return fopsChangeRequest;
    }
}