/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class FullviewDataBuilder {
    //the instance to build
    private FullviewData fullviewData;

    /**
     * Default constructor to initialize the instance
     */
    public FullviewDataBuilder() {
        fullviewData = new FullviewData();
    }

    public FullviewDataBuilder file(List<BaseFileMetadata> file) {
        fullviewData.setFile(file);
        return this;
    }

    public FullviewDataBuilder folder(List<BaseFolderMetadata> folder) {
        fullviewData.setFolder(folder);
        return this;
    }

    public FullviewDataBuilder deleted(DeletedList deleted) {
        fullviewData.setDeleted(deleted);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FullviewData build() {
        return fullviewData;
    }
}