/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class FullviewData 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5658649626003727439L;
    private List<BaseFileMetadata> file;
    private List<BaseFolderMetadata> folder;
    private DeletedList deleted;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("file")
    public List<BaseFileMetadata> getFile ( ) { 
        return this.file;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("file")
    public void setFile (List<BaseFileMetadata> value) { 
        this.file = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("folder")
    public List<BaseFolderMetadata> getFolder ( ) { 
        return this.folder;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("folder")
    public void setFolder (List<BaseFolderMetadata> value) { 
        this.folder = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deleted")
    public DeletedList getDeleted ( ) { 
        return this.deleted;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deleted")
    public void setDeleted (DeletedList value) { 
        this.deleted = value;
    }
 
}
 