/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class FullviewResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4903789061555933099L;
    private FullviewData data;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("data")
    public FullviewData getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("data")
    public void setData (FullviewData value) { 
        this.data = value;
    }
 
}
 