/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class LinkResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5693422885003265061L;
    private String rel;
    private String link;
    /** GETTER
     * The link identifier.
     */
    @JsonGetter("rel")
    public String getRel ( ) { 
        return this.rel;
    }
    
    /** SETTER
     * The link identifier.
     */
    @JsonSetter("rel")
    public void setRel (String value) { 
        this.rel = value;
    }
 
    /** GETTER
     * The URI of the link.
     */
    @JsonGetter("link")
    public String getLink ( ) { 
        return this.link;
    }
    
    /** SETTER
     * The URI of the link.
     */
    @JsonSetter("link")
    public void setLink (String value) { 
        this.link = value;
    }
 
}
 