/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class MetadataResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5219779522359863433L;
    private FileMetadata file;
    private ParentFolderMetadata folder;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("file")
    public FileMetadata getFile ( ) { 
        return this.file;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("file")
    public void setFile (FileMetadata value) { 
        this.file = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("folder")
    public ParentFolderMetadata getFolder ( ) { 
        return this.folder;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("folder")
    public void setFolder (ParentFolderMetadata value) { 
        this.folder = value;
    }
 
}
 