/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class MetadataUpdateRequestBuilder {
    //the instance to build
    private MetadataUpdateRequest metadataUpdateRequest;

    /**
     * Default constructor to initialize the instance
     */
    public MetadataUpdateRequestBuilder() {
        metadataUpdateRequest = new MetadataUpdateRequest();
    }

    /**
     * The name of the system attribute to be updated
     */
    public MetadataUpdateRequestBuilder name(String name) {
        metadataUpdateRequest.setName(name);
        return this;
    }

    /**
     * The value of the system attribute
     */
    public MetadataUpdateRequestBuilder value(String value) {
        metadataUpdateRequest.setValue(value);
        return this;
    }

    /**
     * The URI to the file which needs to be updated
     */
    public MetadataUpdateRequestBuilder uri(String uri) {
        metadataUpdateRequest.setUri(uri);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MetadataUpdateRequest build() {
        return metadataUpdateRequest;
    }
}