/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class MetadataUpdateRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4818750565011535511L;
    private String name;
    private String value;
    private String uri;
    /** GETTER
     * The name of the system attribute to be updated
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * The name of the system attribute to be updated
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * The value of the system attribute
     */
    @JsonGetter("value")
    public String getValue ( ) { 
        return this.value;
    }
    
    /** SETTER
     * The value of the system attribute
     */
    @JsonSetter("value")
    public void setValue (String value) { 
        this.value = value;
    }
 
    /** GETTER
     * The URI to the file which needs to be updated
     */
    @JsonGetter("uri")
    public String getUri ( ) { 
        return this.uri;
    }
    
    /** SETTER
     * The URI to the file which needs to be updated
     */
    @JsonSetter("uri")
    public void setUri (String value) { 
        this.uri = value;
    }
 
}
 