/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class MetadataResponseBuilder {
    //the instance to build
    private MetadataResponse metadataResponse;

    /**
     * Default constructor to initialize the instance
     */
    public MetadataResponseBuilder() {
        metadataResponse = new MetadataResponse();
    }

    public MetadataResponseBuilder file(FileMetadata file) {
        metadataResponse.setFile(file);
        return this;
    }

    public MetadataResponseBuilder folder(ParentFolderMetadata folder) {
        metadataResponse.setFolder(folder);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MetadataResponse build() {
        return metadataResponse;
    }
}