/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ParentFolderMetadataBuilder {
    //the instance to build
    private ParentFolderMetadata parentFolderMetadata;

    /**
     * Default constructor to initialize the instance
     */
    public ParentFolderMetadataBuilder() {
        parentFolderMetadata = new ParentFolderMetadata();
    }

    public ParentFolderMetadataBuilder file(List<FileMetadata> file) {
        parentFolderMetadata.setFile(file);
        return this;
    }

    public ParentFolderMetadataBuilder folder(List<FolderMetadata> folder) {
        parentFolderMetadata.setFolder(folder);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ParentFolderMetadata build() {
        return parentFolderMetadata;
    }
}