/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class PlaylistAddRequestBuilder {
    //the instance to build
    private PlaylistAddRequest playlistAddRequest;

    /**
     * Default constructor to initialize the instance
     */
    public PlaylistAddRequestBuilder() {
        playlistAddRequest = new PlaylistAddRequest();
    }

    /**
     * An array of paths to items.
     */
    public PlaylistAddRequestBuilder add(List<String> add) {
        playlistAddRequest.setAdd(add);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PlaylistAddRequest build() {
        return playlistAddRequest;
    }
}