/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PlaylistItem 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5307701272185650188L;
    private String filename;
    private String path;
    private String mimeType;
    private int size;
    private String versionCreated;
    private PlaylistItem fileAttribute;
    private String contentToken;
    private String checksum;
    private boolean contentAccessible;
    private String extension;
    private Object tags;
    private String uri;
    /** GETTER
     * Name of the file
     */
    @JsonGetter("filename")
    public String getFilename ( ) { 
        return this.filename;
    }
    
    /** SETTER
     * Name of the file
     */
    @JsonSetter("filename")
    public void setFilename (String value) { 
        this.filename = value;
    }
 
    /** GETTER
     * Path of the file
     */
    @JsonGetter("path")
    public String getPath ( ) { 
        return this.path;
    }
    
    /** SETTER
     * Path of the file
     */
    @JsonSetter("path")
    public void setPath (String value) { 
        this.path = value;
    }
 
    /** GETTER
     * Type of content
     */
    @JsonGetter("mimeType")
    public String getMimeType ( ) { 
        return this.mimeType;
    }
    
    /** SETTER
     * Type of content
     */
    @JsonSetter("mimeType")
    public void setMimeType (String value) { 
        this.mimeType = value;
    }
 
    /** GETTER
     * Size of the item
     */
    @JsonGetter("size")
    public int getSize ( ) { 
        return this.size;
    }
    
    /** SETTER
     * Size of the item
     */
    @JsonSetter("size")
    public void setSize (int value) { 
        this.size = value;
    }
 
    /** GETTER
     * Timestamp of version created date
     */
    @JsonGetter("versionCreated")
    public String getVersionCreated ( ) { 
        return this.versionCreated;
    }
    
    /** SETTER
     * Timestamp of version created date
     */
    @JsonSetter("versionCreated")
    public void setVersionCreated (String value) { 
        this.versionCreated = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fileAttribute")
    public PlaylistItem getFileAttribute ( ) { 
        return this.fileAttribute;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fileAttribute")
    public void setFileAttribute (PlaylistItem value) { 
        this.fileAttribute = value;
    }
 
    /** GETTER
     * Unique token for content
     */
    @JsonGetter("contentToken")
    public String getContentToken ( ) { 
        return this.contentToken;
    }
    
    /** SETTER
     * Unique token for content
     */
    @JsonSetter("contentToken")
    public void setContentToken (String value) { 
        this.contentToken = value;
    }
 
    /** GETTER
     * Checksum detail
     */
    @JsonGetter("checksum")
    public String getChecksum ( ) { 
        return this.checksum;
    }
    
    /** SETTER
     * Checksum detail
     */
    @JsonSetter("checksum")
    public void setChecksum (String value) { 
        this.checksum = value;
    }
 
    /** GETTER
     * Show accessibility of the content
     */
    @JsonGetter("contentAccessible")
    public boolean getContentAccessible ( ) { 
        return this.contentAccessible;
    }
    
    /** SETTER
     * Show accessibility of the content
     */
    @JsonSetter("contentAccessible")
    public void setContentAccessible (boolean value) { 
        this.contentAccessible = value;
    }
 
    /** GETTER
     * File extension
     */
    @JsonGetter("extension")
    public String getExtension ( ) { 
        return this.extension;
    }
    
    /** SETTER
     * File extension
     */
    @JsonSetter("extension")
    public void setExtension (String value) { 
        this.extension = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("tags")
    public Object getTags ( ) { 
        return this.tags;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("tags")
    public void setTags (Object value) { 
        this.tags = value;
    }
 
    /** GETTER
     * Unique identifier of the resource
     */
    @JsonGetter("uri")
    public String getUri ( ) { 
        return this.uri;
    }
    
    /** SETTER
     * Unique identifier of the resource
     */
    @JsonSetter("uri")
    public void setUri (String value) { 
        this.uri = value;
    }
 
}
 