/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PlaylistBase 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5379177189786202581L;
    private String name;
    private String type;
    /** GETTER
     * The name of the playlist
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * The name of the playlist
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * The type of the playlist. Can be one of 'image', 'music', 'video' or 'image-video'
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * The type of the playlist. Can be one of 'image', 'music', 'video' or 'image-video'
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
}
 