/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class PlaylistBaseBuilder {
    //the instance to build
    private PlaylistBase playlistBase;

    /**
     * Default constructor to initialize the instance
     */
    public PlaylistBaseBuilder() {
        playlistBase = new PlaylistBase();
    }

    /**
     * The name of the playlist
     */
    public PlaylistBaseBuilder name(String name) {
        playlistBase.setName(name);
        return this;
    }

    /**
     * The type of the playlist. Can be one of 'image', 'music', 'video' or 'image-video'
     */
    public PlaylistBaseBuilder type(String type) {
        playlistBase.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PlaylistBase build() {
        return playlistBase;
    }
}