/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Playlist 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5505671751480617816L;
    private String uid;
    private String name;
    private String type;
    private String mimeTypeRegex;
    private String creationDate;
    private String lastModifiedDate;
    private String uri;
    private List<String> paths;
    private List<ShareAssociation> shareAssociation;
    /** GETTER
     * The uid of the playlist
     */
    @JsonGetter("uid")
    public String getUid ( ) { 
        return this.uid;
    }
    
    /** SETTER
     * The uid of the playlist
     */
    @JsonSetter("uid")
    public void setUid (String value) { 
        this.uid = value;
    }
 
    /** GETTER
     * The name of the playlist
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * The name of the playlist
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * The type of playlist
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * The type of playlist
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * Regex pattern for playlist
     */
    @JsonGetter("mimeTypeRegex")
    public String getMimeTypeRegex ( ) { 
        return this.mimeTypeRegex;
    }
    
    /** SETTER
     * Regex pattern for playlist
     */
    @JsonSetter("mimeTypeRegex")
    public void setMimeTypeRegex (String value) { 
        this.mimeTypeRegex = value;
    }
 
    /** GETTER
     * Timestamp for creation date of playlist
     */
    @JsonGetter("creationDate")
    public String getCreationDate ( ) { 
        return this.creationDate;
    }
    
    /** SETTER
     * Timestamp for creation date of playlist
     */
    @JsonSetter("creationDate")
    public void setCreationDate (String value) { 
        this.creationDate = value;
    }
 
    /** GETTER
     * Timestamp for last modified date of playlist
     */
    @JsonGetter("lastModifiedDate")
    public String getLastModifiedDate ( ) { 
        return this.lastModifiedDate;
    }
    
    /** SETTER
     * Timestamp for last modified date of playlist
     */
    @JsonSetter("lastModifiedDate")
    public void setLastModifiedDate (String value) { 
        this.lastModifiedDate = value;
    }
 
    /** GETTER
     * Unique identifier of the resource
     */
    @JsonGetter("uri")
    public String getUri ( ) { 
        return this.uri;
    }
    
    /** SETTER
     * Unique identifier of the resource
     */
    @JsonSetter("uri")
    public void setUri (String value) { 
        this.uri = value;
    }
 
    /** GETTER
     * Array of paths
     */
    @JsonGetter("paths")
    public List<String> getPaths ( ) { 
        return this.paths;
    }
    
    /** SETTER
     * Array of paths
     */
    @JsonSetter("paths")
    public void setPaths (List<String> value) { 
        this.paths = value;
    }
 
    /** GETTER
     * Array of shareAssociation
     */
    @JsonGetter("shareAssociation")
    public List<ShareAssociation> getShareAssociation ( ) { 
        return this.shareAssociation;
    }
    
    /** SETTER
     * Array of shareAssociation
     */
    @JsonSetter("shareAssociation")
    public void setShareAssociation (List<ShareAssociation> value) { 
        this.shareAssociation = value;
    }
 
}
 