/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class PlaylistAddResponseBuilder {
    //the instance to build
    private PlaylistAddResponse playlistAddResponse;

    /**
     * Default constructor to initialize the instance
     */
    public PlaylistAddResponseBuilder() {
        playlistAddResponse = new PlaylistAddResponse();
    }

    /**
     * List of paths
     */
    public PlaylistAddResponseBuilder paths(List<String> paths) {
        playlistAddResponse.setPaths(paths);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PlaylistAddResponse build() {
        return playlistAddResponse;
    }
}