/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class PlaylistRequestBuilder {
    //the instance to build
    private PlaylistRequest playlistRequest;

    /**
     * Default constructor to initialize the instance
     */
    public PlaylistRequestBuilder() {
        playlistRequest = new PlaylistRequest();
    }

    /**
     * Name of the playlist.
     */
    public PlaylistRequestBuilder name(String name) {
        playlistRequest.setName(name);
        return this;
    }

    /**
     * An array of paths to items.
     */
    public PlaylistRequestBuilder paths(List<String> paths) {
        playlistRequest.setPaths(paths);
        return this;
    }

    /**
     * The type of the playlist. Can be one of 'image', 'music', 'video' or 'image-video'
     */
    public PlaylistRequestBuilder type(String type) {
        playlistRequest.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PlaylistRequest build() {
        return playlistRequest;
    }
}