/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class PlaylistBuilder {
    //the instance to build
    private Playlist playlist;

    /**
     * Default constructor to initialize the instance
     */
    public PlaylistBuilder() {
        playlist = new Playlist();
    }

    /**
     * The uid of the playlist
     */
    public PlaylistBuilder uid(String uid) {
        playlist.setUid(uid);
        return this;
    }

    /**
     * The name of the playlist
     */
    public PlaylistBuilder name(String name) {
        playlist.setName(name);
        return this;
    }

    /**
     * The type of playlist
     */
    public PlaylistBuilder type(String type) {
        playlist.setType(type);
        return this;
    }

    /**
     * Regex pattern for playlist
     */
    public PlaylistBuilder mimeTypeRegex(String mimeTypeRegex) {
        playlist.setMimeTypeRegex(mimeTypeRegex);
        return this;
    }

    /**
     * Timestamp for creation date of playlist
     */
    public PlaylistBuilder creationDate(String creationDate) {
        playlist.setCreationDate(creationDate);
        return this;
    }

    /**
     * Timestamp for last modified date of playlist
     */
    public PlaylistBuilder lastModifiedDate(String lastModifiedDate) {
        playlist.setLastModifiedDate(lastModifiedDate);
        return this;
    }

    /**
     * Unique identifier of the resource
     */
    public PlaylistBuilder uri(String uri) {
        playlist.setUri(uri);
        return this;
    }

    /**
     * Array of paths
     */
    public PlaylistBuilder paths(List<String> paths) {
        playlist.setPaths(paths);
        return this;
    }

    /**
     * Array of shareAssociation
     */
    public PlaylistBuilder shareAssociation(List<ShareAssociation> shareAssociation) {
        playlist.setShareAssociation(shareAssociation);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Playlist build() {
        return playlist;
    }
}