/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PlaylistAddResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5602519075592778322L;
    private List<String> paths;
    /** GETTER
     * List of paths
     */
    @JsonGetter("paths")
    public List<String> getPaths ( ) { 
        return this.paths;
    }
    
    /** SETTER
     * List of paths
     */
    @JsonSetter("paths")
    public void setPaths (List<String> value) { 
        this.paths = value;
    }
 
}
 