/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ResourceResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5596117654803383825L;
    private String name;
    private String type;
    private String uid;
    private String subType;
    private String location;
    private Integer size;
    private String resourceId;
    private String contentToken;
    private String checksum;
    private String lastModifiedDate;
    /** GETTER
     * Name of the resource.
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Name of the resource.
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Type of the resource.
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Type of the resource.
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * The resource identifier.
     */
    @JsonGetter("uid")
    public String getUid ( ) { 
        return this.uid;
    }
    
    /** SETTER
     * The resource identifier.
     */
    @JsonSetter("uid")
    public void setUid (String value) { 
        this.uid = value;
    }
 
    /** GETTER
     * SubType of the resource.
     */
    @JsonGetter("subType")
    public String getSubType ( ) { 
        return this.subType;
    }
    
    /** SETTER
     * SubType of the resource.
     */
    @JsonSetter("subType")
    public void setSubType (String value) { 
        this.subType = value;
    }
 
    /** GETTER
     * Location of the resource.
     */
    @JsonGetter("location")
    public String getLocation ( ) { 
        return this.location;
    }
    
    /** SETTER
     * Location of the resource.
     */
    @JsonSetter("location")
    public void setLocation (String value) { 
        this.location = value;
    }
 
    /** GETTER
     * Size of the resource.
     */
    @JsonGetter("size")
    public Integer getSize ( ) { 
        return this.size;
    }
    
    /** SETTER
     * Size of the resource.
     */
    @JsonSetter("size")
    public void setSize (Integer value) { 
        this.size = value;
    }
 
    /** GETTER
     * Id of the resource.
     */
    @JsonGetter("resourceId")
    public String getResourceId ( ) { 
        return this.resourceId;
    }
    
    /** SETTER
     * Id of the resource.
     */
    @JsonSetter("resourceId")
    public void setResourceId (String value) { 
        this.resourceId = value;
    }
 
    /** GETTER
     * ContentToken of the resource.
     */
    @JsonGetter("contentToken")
    public String getContentToken ( ) { 
        return this.contentToken;
    }
    
    /** SETTER
     * ContentToken of the resource.
     */
    @JsonSetter("contentToken")
    public void setContentToken (String value) { 
        this.contentToken = value;
    }
 
    /** GETTER
     * Checksum of the resource.
     */
    @JsonGetter("checksum")
    public String getChecksum ( ) { 
        return this.checksum;
    }
    
    /** SETTER
     * Checksum of the resource.
     */
    @JsonSetter("checksum")
    public void setChecksum (String value) { 
        this.checksum = value;
    }
 
    /** GETTER
     * LastModifiedDate of the resource.
     */
    @JsonGetter("lastModifiedDate")
    public String getLastModifiedDate ( ) { 
        return this.lastModifiedDate;
    }
    
    /** SETTER
     * LastModifiedDate of the resource.
     */
    @JsonSetter("lastModifiedDate")
    public void setLastModifiedDate (String value) { 
        this.lastModifiedDate = value;
    }
 
}
 