/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ResourceRequestBuilder {
    //the instance to build
    private ResourceRequest resourceRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ResourceRequestBuilder() {
        resourceRequest = new ResourceRequest();
    }

    /**
     * Name of the resource.
     */
    public ResourceRequestBuilder name(String name) {
        resourceRequest.setName(name);
        return this;
    }

    /**
     * Location of the resource. This is a URI value obtained from a fullview, metadata, or playlist response
     */
    public ResourceRequestBuilder location(String location) {
        resourceRequest.setLocation(location);
        return this;
    }

    /**
     * Type of the resource: file/folder/playlist
     */
    public ResourceRequestBuilder type(String type) {
        resourceRequest.setType(type);
        return this;
    }

    /**
     * (Optional) subtype of the resource: image/video/audio.  Used to aid playback of the file when viewed in a browser
     */
    public ResourceRequestBuilder subType(String subType) {
        resourceRequest.setSubType(subType);
        return this;
    }

    /**
     * Size of the resource. Mandatory in case of file share only.
     */
    public ResourceRequestBuilder size(Integer size) {
        resourceRequest.setSize(size);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ResourceRequest build() {
        return resourceRequest;
    }
}