/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ResourceResponseBuilder {
    //the instance to build
    private ResourceResponse resourceResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ResourceResponseBuilder() {
        resourceResponse = new ResourceResponse();
    }

    /**
     * Name of the resource.
     */
    public ResourceResponseBuilder name(String name) {
        resourceResponse.setName(name);
        return this;
    }

    /**
     * Type of the resource.
     */
    public ResourceResponseBuilder type(String type) {
        resourceResponse.setType(type);
        return this;
    }

    /**
     * The resource identifier.
     */
    public ResourceResponseBuilder uid(String uid) {
        resourceResponse.setUid(uid);
        return this;
    }

    /**
     * SubType of the resource.
     */
    public ResourceResponseBuilder subType(String subType) {
        resourceResponse.setSubType(subType);
        return this;
    }

    /**
     * Location of the resource.
     */
    public ResourceResponseBuilder location(String location) {
        resourceResponse.setLocation(location);
        return this;
    }

    /**
     * Size of the resource.
     */
    public ResourceResponseBuilder size(Integer size) {
        resourceResponse.setSize(size);
        return this;
    }

    /**
     * Id of the resource.
     */
    public ResourceResponseBuilder resourceId(String resourceId) {
        resourceResponse.setResourceId(resourceId);
        return this;
    }

    /**
     * ContentToken of the resource.
     */
    public ResourceResponseBuilder contentToken(String contentToken) {
        resourceResponse.setContentToken(contentToken);
        return this;
    }

    /**
     * Checksum of the resource.
     */
    public ResourceResponseBuilder checksum(String checksum) {
        resourceResponse.setChecksum(checksum);
        return this;
    }

    /**
     * LastModifiedDate of the resource.
     */
    public ResourceResponseBuilder lastModifiedDate(String lastModifiedDate) {
        resourceResponse.setLastModifiedDate(lastModifiedDate);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ResourceResponse build() {
        return resourceResponse;
    }
}