/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ResourceRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4857434727656293197L;
    private String name;
    private String location;
    private String type;
    private String subType;
    private Integer size;
    /** GETTER
     * Name of the resource.
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Name of the resource.
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Location of the resource. This is a URI value obtained from a fullview, metadata, or playlist response
     */
    @JsonGetter("location")
    public String getLocation ( ) { 
        return this.location;
    }
    
    /** SETTER
     * Location of the resource. This is a URI value obtained from a fullview, metadata, or playlist response
     */
    @JsonSetter("location")
    public void setLocation (String value) { 
        this.location = value;
    }
 
    /** GETTER
     * Type of the resource: file/folder/playlist
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Type of the resource: file/folder/playlist
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * (Optional) subtype of the resource: image/video/audio.  Used to aid playback of the file when viewed in a browser
     */
    @JsonGetter("subType")
    public String getSubType ( ) { 
        return this.subType;
    }
    
    /** SETTER
     * (Optional) subtype of the resource: image/video/audio.  Used to aid playback of the file when viewed in a browser
     */
    @JsonSetter("subType")
    public void setSubType (String value) { 
        this.subType = value;
    }
 
    /** GETTER
     * Size of the resource. Mandatory in case of file share only.
     */
    @JsonGetter("size")
    public Integer getSize ( ) { 
        return this.size;
    }
    
    /** SETTER
     * Size of the resource. Mandatory in case of file share only.
     */
    @JsonSetter("size")
    public void setSize (Integer value) { 
        this.size = value;
    }
 
}
 