/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SearchresultResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5362495908412411144L;
    private long count;
    private List<FileMetadata> file;
    private List<FolderMetadata> folder;
    /** GETTER
     * Total number of search matches
     */
    @JsonGetter("count")
    public long getCount ( ) { 
        return this.count;
    }
    
    /** SETTER
     * Total number of search matches
     */
    @JsonSetter("count")
    public void setCount (long value) { 
        this.count = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("file")
    public List<FileMetadata> getFile ( ) { 
        return this.file;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("file")
    public void setFile (List<FileMetadata> value) { 
        this.file = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("folder")
    public List<FolderMetadata> getFolder ( ) { 
        return this.folder;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("folder")
    public void setFolder (List<FolderMetadata> value) { 
        this.folder = value;
    }
 
}
 