/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ShareResponseListBuilder {
    //the instance to build
    private ShareResponseList shareResponseList;

    /**
     * Default constructor to initialize the instance
     */
    public ShareResponseListBuilder() {
        shareResponseList = new ShareResponseList();
    }

    /**
     * The total number of shares
     */
    public ShareResponseListBuilder count(Integer count) {
        shareResponseList.setCount(count);
        return this;
    }

    public ShareResponseListBuilder links(List<LinkResponse> links) {
        shareResponseList.setLinks(links);
        return this;
    }

    public ShareResponseListBuilder share(List<ShareResponse> share) {
        shareResponseList.setShare(share);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ShareResponseList build() {
        return shareResponseList;
    }
}