/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ShareResponseBuilder {
    //the instance to build
    private ShareResponse shareResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ShareResponseBuilder() {
        shareResponse = new ShareResponse();
    }

    /**
     * The name of the share.
     */
    public ShareResponseBuilder name(String name) {
        shareResponse.setName(name);
        return this;
    }

    public ShareResponseBuilder links(List<LinkResponse> links) {
        shareResponse.setLinks(links);
        return this;
    }

    /**
     * The resource identifier.
     */
    public ShareResponseBuilder uid(String uid) {
        shareResponse.setUid(uid);
        return this;
    }

    /**
     * The owner of the share
     */
    public ShareResponseBuilder owner(Object owner) {
        shareResponse.setOwner(owner);
        return this;
    }

    /**
     * The sharer of the share
     */
    public ShareResponseBuilder sharer(Object sharer) {
        shareResponse.setSharer(sharer);
        return this;
    }

    /**
     * The total count of shared resources.
     */
    public ShareResponseBuilder totalResourceCount(Integer totalResourceCount) {
        shareResponse.setTotalResourceCount(totalResourceCount);
        return this;
    }

    /**
     * The time to live of the share in seconds.
     */
    public ShareResponseBuilder expiresIn(Integer expiresIn) {
        shareResponse.setExpiresIn(expiresIn);
        return this;
    }

    /**
     * Expiration date on the share.
     */
    public ShareResponseBuilder expirationDate(String expirationDate) {
        shareResponse.setExpirationDate(expirationDate);
        return this;
    }

    /**
     * The date and time the share was created.
     */
    public ShareResponseBuilder creationDate(String creationDate) {
        shareResponse.setCreationDate(creationDate);
        return this;
    }

    /**
     * The date and time the share was last modified from the perspective of the owner.
     */
    public ShareResponseBuilder lastModifiedDate(String lastModifiedDate) {
        shareResponse.setLastModifiedDate(lastModifiedDate);
        return this;
    }

    /**
     * The date and time the share was last modified from the perspective of a member.
     */
    public ShareResponseBuilder inboundLastModifiedDate(String inboundLastModifiedDate) {
        shareResponse.setInboundLastModifiedDate(inboundLastModifiedDate);
        return this;
    }

    /**
     * The invite key of a public share.
     */
    public ShareResponseBuilder publicInviteKey(String publicInviteKey) {
        shareResponse.setPublicInviteKey(publicInviteKey);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ShareResponse build() {
        return shareResponse;
    }
}