/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ShareAssociationBuilder {
    //the instance to build
    private ShareAssociation shareAssociation;

    /**
     * Default constructor to initialize the instance
     */
    public ShareAssociationBuilder() {
        shareAssociation = new ShareAssociation();
    }

    /**
     * Unique id
     */
    public ShareAssociationBuilder uid(String uid) {
        shareAssociation.setUid(uid);
        return this;
    }

    /**
     * Visibility of share association
     */
    public ShareAssociationBuilder visibility(String visibility) {
        shareAssociation.setVisibility(visibility);
        return this;
    }

    /**
     * Name
     */
    public ShareAssociationBuilder name(String name) {
        shareAssociation.setName(name);
        return this;
    }

    /**
     * Type of share association
     */
    public ShareAssociationBuilder type(String type) {
        shareAssociation.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ShareAssociation build() {
        return shareAssociation;
    }
}