/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ShareAssociation 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5391072014499165182L;
    private String uid;
    private String visibility;
    private String name;
    private String type;
    /** GETTER
     * Unique id
     */
    @JsonGetter("uid")
    public String getUid ( ) { 
        return this.uid;
    }
    
    /** SETTER
     * Unique id
     */
    @JsonSetter("uid")
    public void setUid (String value) { 
        this.uid = value;
    }
 
    /** GETTER
     * Visibility of share association
     */
    @JsonGetter("visibility")
    public String getVisibility ( ) { 
        return this.visibility;
    }
    
    /** SETTER
     * Visibility of share association
     */
    @JsonSetter("visibility")
    public void setVisibility (String value) { 
        this.visibility = value;
    }
 
    /** GETTER
     * Name
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Name
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Type of share association
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Type of share association
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
}
 