/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ShareResponseList 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4710995247597829475L;
    private Integer count;
    private List<LinkResponse> links;
    private List<ShareResponse> share;
    /** GETTER
     * The total number of shares
     */
    @JsonGetter("count")
    public Integer getCount ( ) { 
        return this.count;
    }
    
    /** SETTER
     * The total number of shares
     */
    @JsonSetter("count")
    public void setCount (Integer value) { 
        this.count = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("links")
    public List<LinkResponse> getLinks ( ) { 
        return this.links;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("links")
    public void setLinks (List<LinkResponse> value) { 
        this.links = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("share")
    public List<ShareResponse> getShare ( ) { 
        return this.share;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("share")
    public void setShare (List<ShareResponse> value) { 
        this.share = value;
    }
 
}
 