/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class TagsResponseBuilder {
    //the instance to build
    private TagsResponse tagsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public TagsResponseBuilder() {
        tagsResponse = new TagsResponse();
    }

    /**
     * A set of Tags
     */
    public TagsResponseBuilder tags(String tags) {
        tagsResponse.setTags(tags);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TagsResponse build() {
        return tagsResponse;
    }
}