/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TagsResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5694897269839685286L;
    private String tags;
    /** GETTER
     * A set of Tags
     */
    @JsonGetter("Tags")
    public String getTags ( ) { 
        return this.tags;
    }
    
    /** SETTER
     * A set of Tags
     */
    @JsonSetter("Tags")
    public void setTags (String value) { 
        this.tags = value;
    }
 
}
 