/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class TrashResponseBuilder {
    //the instance to build
    private TrashResponse trashResponse;

    /**
     * Default constructor to initialize the instance
     */
    public TrashResponseBuilder() {
        trashResponse = new TrashResponse();
    }

    /**
     * Total number of search matches
     */
    public TrashResponseBuilder count(long count) {
        trashResponse.setCount(count);
        return this;
    }

    public TrashResponseBuilder data(TrashData data) {
        trashResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TrashResponse build() {
        return trashResponse;
    }
}