/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TrashResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5108025408641513773L;
    private long count;
    private TrashData data;
    /** GETTER
     * Total number of search matches
     */
    @JsonGetter("count")
    public long getCount ( ) { 
        return this.count;
    }
    
    /** SETTER
     * Total number of search matches
     */
    @JsonSetter("count")
    public void setCount (long value) { 
        this.count = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("data")
    public TrashData getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("data")
    public void setData (TrashData value) { 
        this.data = value;
    }
 
}
 