/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class TrashDataBuilder {
    //the instance to build
    private TrashData trashData;

    /**
     * Default constructor to initialize the instance
     */
    public TrashDataBuilder() {
        trashData = new TrashData();
    }

    public TrashDataBuilder file(List<BaseFileMetadata> file) {
        trashData.setFile(file);
        return this;
    }

    public TrashDataBuilder folder(List<BaseFolderMetadata> folder) {
        trashData.setFolder(folder);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TrashData build() {
        return trashData;
    }
}