/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class UpdateTagsRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4656818102163365097L;
    private String uri;
    private String tags;
    private Boolean createVersion = false;
    /** GETTER
     * URI of the resource. This is a URI value obtained from a fullview or metadata response
     */
    @JsonGetter("uri")
    public String getUri ( ) { 
        return this.uri;
    }
    
    /** SETTER
     * URI of the resource. This is a URI value obtained from a fullview or metadata response
     */
    @JsonSetter("uri")
    public void setUri (String value) { 
        this.uri = value;
    }
 
    /** GETTER
     * A set of Tags
     */
    @JsonGetter("Tags")
    public String getTags ( ) { 
        return this.tags;
    }
    
    /** SETTER
     * A set of Tags
     */
    @JsonSetter("Tags")
    public void setTags (String value) { 
        this.tags = value;
    }
 
    /** GETTER
     * If 'true', creates a new version of the file or folder. Defaults to 'false'.
     */
    @JsonGetter("createVersion")
    public Boolean getCreateVersion ( ) { 
        return this.createVersion;
    }
    
    /** SETTER
     * If 'true', creates a new version of the file or folder. Defaults to 'false'.
     */
    @JsonSetter("createVersion")
    public void setCreateVersion (Boolean value) { 
        this.createVersion = value;
    }
 
}
 