/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class UpdateTagsRequestBuilder {
    //the instance to build
    private UpdateTagsRequest updateTagsRequest;

    /**
     * Default constructor to initialize the instance
     */
    public UpdateTagsRequestBuilder() {
        updateTagsRequest = new UpdateTagsRequest();
    }

    /**
     * URI of the resource. This is a URI value obtained from a fullview or metadata response
     */
    public UpdateTagsRequestBuilder uri(String uri) {
        updateTagsRequest.setUri(uri);
        return this;
    }

    /**
     * A set of Tags
     */
    public UpdateTagsRequestBuilder tags(String tags) {
        updateTagsRequest.setTags(tags);
        return this;
    }

    /**
     * If 'true', creates a new version of the file or folder. Defaults to 'false'.
     */
    public UpdateTagsRequestBuilder createVersion(Boolean createVersion) {
        updateTagsRequest.setCreateVersion(createVersion);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdateTagsRequest build() {
        return updateTagsRequest;
    }
}