/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class UploadurlsBuilder {
    //the instance to build
    private Uploadurls uploadurls;

    /**
     * Default constructor to initialize the instance
     */
    public UploadurlsBuilder() {
        uploadurls = new Uploadurls();
    }

    /**
     * The upload url with the uploadid to upload the binary content of the file.
     */
    public UploadurlsBuilder uploadurl(String uploadurl) {
        uploadurls.setUploadurl(uploadurl);
        return this;
    }

    /**
     * The commit url to create the file after binary content is uploaded in chunks.
     */
    public UploadurlsBuilder commiturl(String commiturl) {
        uploadurls.setCommiturl(commiturl);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Uploadurls build() {
        return uploadurls;
    }
}