/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Uploadurls 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4955030325630035330L;
    private String uploadurl;
    private String commiturl;
    /** GETTER
     * The upload url with the uploadid to upload the binary content of the file.
     */
    @JsonGetter("uploadurl")
    public String getUploadurl ( ) { 
        return this.uploadurl;
    }
    
    /** SETTER
     * The upload url with the uploadid to upload the binary content of the file.
     */
    @JsonSetter("uploadurl")
    public void setUploadurl (String value) { 
        this.uploadurl = value;
    }
 
    /** GETTER
     * The commit url to create the file after binary content is uploaded in chunks.
     */
    @JsonGetter("commiturl")
    public String getCommiturl ( ) { 
        return this.commiturl;
    }
    
    /** SETTER
     * The commit url to create the file after binary content is uploaded in chunks.
     */
    @JsonSetter("commiturl")
    public void setCommiturl (String value) { 
        this.commiturl = value;
    }
 
}
 