/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Usage 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4620052557429869967L;
    private long quota;
    private long quotaUsed;
    /** GETTER
     * Total quota space available to the user on the cloud in bytes
     */
    @JsonGetter("quota")
    public long getQuota ( ) { 
        return this.quota;
    }
    
    /** SETTER
     * Total quota space available to the user on the cloud in bytes
     */
    @JsonSetter("quota")
    public void setQuota (long value) { 
        this.quota = value;
    }
 
    /** GETTER
     * Total quota space used in bytes
     */
    @JsonGetter("quotaUsed")
    public long getQuotaUsed ( ) { 
        return this.quotaUsed;
    }
    
    /** SETTER
     * Total quota space used in bytes
     */
    @JsonSetter("quotaUsed")
    public void setQuotaUsed (long value) { 
        this.quotaUsed = value;
    }
 
}
 