/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;

public class ViewUidBuilder {
    //the instance to build
    private ViewUid viewUid;

    /**
     * Default constructor to initialize the instance
     */
    public ViewUidBuilder() {
        viewUid = new ViewUid();
    }

    /**
     * Shared Type
     */
    public ViewUidBuilder type(String type) {
        viewUid.setType(type);
        return this;
    }

    /**
     * Type of view
     */
    public ViewUidBuilder viewType(String viewType) {
        viewUid.setViewType(viewType);
        return this;
    }

    /**
     * Unique id of view
     */
    public ViewUidBuilder uid(String uid) {
        viewUid.setUid(uid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ViewUid build() {
        return viewUid;
    }
}