/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ViewUid 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5343738268642846892L;
    private String type;
    private String viewType;
    private String uid;
    /** GETTER
     * Shared Type
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Shared Type
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * Type of view
     */
    @JsonGetter("viewType")
    public String getViewType ( ) { 
        return this.viewType;
    }
    
    /** SETTER
     * Type of view
     */
    @JsonSetter("viewType")
    public void setViewType (String value) { 
        this.viewType = value;
    }
 
    /** GETTER
     * Unique id of view
     */
    @JsonGetter("uid")
    public String getUid ( ) { 
        return this.uid;
    }
    
    /** SETTER
     * Unique id of view
     */
    @JsonSetter("uid")
    public void setUid (String value) { 
        this.uid = value;
    }
 
}
 