/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.fasterxml.jackson.core.type.TypeReference;

import com.verizon.cloudapi.api.*;
import com.verizon.cloudapi.api.models.*;
import com.verizon.cloudapi.api.exceptions.*;
import com.verizon.cloudapi.api.http.client.HttpClient;
import com.verizon.cloudapi.api.http.client.HttpContext;
import com.verizon.cloudapi.api.http.request.HttpRequest;
import com.verizon.cloudapi.api.http.response.HttpResponse;
import com.verizon.cloudapi.api.http.response.HttpStringResponse;
import com.verizon.cloudapi.api.http.client.APICallBack;
import com.verizon.cloudapi.api.controllers.syncwrapper.APICallBackCatcher;

public class ContactsController extends BaseController {    
    //private static variables for the singleton pattern
    private static Object syncObject = new Object();
    private static ContactsController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the ContactsController class 
     */
    public static ContactsController getInstance() {
        synchronized (syncObject) {
            if (null == instance) {
                instance = new ContactsController();
            }
        }
        return instance;
    }

    /**
     * Retrieves all contacts.
     * @return    Returns the Contacts response from the API call 
     */
    public Contacts getContacts(
    ) throws Throwable {
        APICallBackCatcher<Contacts> callback = new APICallBackCatcher<Contacts>();
        getContactsAsync(callback);
        if(!callback.isSuccess())
            throw callback.getError();
        return callback.getResult();
    }

    /**
     * Retrieves all contacts.
     * @return    Returns the void response from the API call 
     */
    public void getContactsAsync(
                final APICallBack<Contacts> callBack
    ) {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri);
        _queryBuilder.append("/contacts");
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>() {
            private static final long serialVersionUID = 4810927041767617418L;
            {
                    put( "user-agent", "APIMATIC 2.0" );
                    put( "accept", "application/json" );
                    put( "Authorization", String.format("Bearer %1$s", Configuration.oAuthAccessToken) );
            }
        };

        //prepare and invoke the API call request to fetch the response
        final HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        //invoke the callback before request if its not null
        if (getHttpCallBack() != null)
        {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        //invoke request and get response
        Runnable _responseTask = new Runnable() {
            public void run() {
                //make the API call
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {

                            //invoke the callback after response if its not null
                            if (getHttpCallBack() != null)	
                            {
                                getHttpCallBack().OnAfterResponse(_context);
                            }

                            //Error handling using HTTP status codes
                            int _responseCode = _response.getStatusCode();
                            if (_responseCode == 401)
                                throw new ErrorResponseException("[Unauthorized] Bearer token is missing, expired, or invalid.", _context);

                            else if (_responseCode == 500)
                                throw new ErrorResponseException("Unexpected Account configuration.", _context);

                            else if (_responseCode == 503)
                                throw new ErrorResponseException("[Service Unavailable] See response body for more detail.", _context);

                            //handle errors defined at the API level
                            validateResponse(_response, _context);

                            //extract result from the http response
                            String _responseBody = ((HttpStringResponse)_response).getBody();
                            Contacts _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<Contacts>(){});

                            //let the caller know of the success
                            callBack.onSuccess(_context, _result);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(_context, error);
                        } catch (IOException ioException) {
                            //let the caller know of the caught IO Exception
                            callBack.onFailure(_context, ioException);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(_context, exception);
                        }
                    }
                    public void onFailure(HttpContext _context, Throwable _error) {
                        //invoke the callback after response if its not null
                        if (getHttpCallBack() != null)	
                            {
                            getHttpCallBack().OnAfterResponse(_context);
                        }

                        //let the caller know of the failure
                        callBack.onFailure(_context, _error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

}