/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api.exceptions;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.verizon.cloudapi.api.http.client.HttpContext;

public class ErrorResponseException 
        extends APIException
        implements java.io.Serializable {
    private static final long serialVersionUID = 5744948101872372665L;
    private String errorCode;
    private String errorDescription;
    /** GETTER
     * A unique code identifying the error
     */
    @JsonGetter("error_code")
    public String getErrorCode ( ) { 
        return this.errorCode;
    }
    
    /** SETTER
     * A unique code identifying the error
     */
    @JsonSetter("error_code")
    private void setErrorCode (String value) { 
        this.errorCode = value;
    }
 
    /** GETTER
     * A detailed description of the error
     */
    @JsonGetter("error_description")
    public String getErrorDescription ( ) { 
        return this.errorDescription;
    }
    
    /** SETTER
     * A detailed description of the error
     */
    @JsonSetter("error_description")
    private void setErrorDescription (String value) { 
        this.errorDescription = value;
    }
 
    /**
     * Initialization constructor
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public ErrorResponseException(String reason, HttpContext context) {
        super(reason, context);
    }
}
 