/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/10/2016
 */
package com.verizon.cloudapi.api;

import com.verizon.cloudapi.api.controllers.*;
import com.verizon.cloudapi.api.http.client.HttpClient;

public class PersonalCloudStorageAPIsClient {
    /**
     * Singleton access to AccountInfo controller
     * @return	Returns the AccountInfoController instance 
     */
    public AccountInfoController getAccountInfo() {
        return AccountInfoController.getInstance();
    }

    /**
     * Singleton access to Tags controller
     * @return	Returns the TagsController instance 
     */
    public TagsController getTags() {
        return TagsController.getInstance();
    }

    /**
     * Singleton access to Contacts controller
     * @return	Returns the ContactsController instance 
     */
    public ContactsController getContacts() {
        return ContactsController.getInstance();
    }

    /**
     * Singleton access to FilesFolders controller
     * @return	Returns the FilesFoldersController instance 
     */
    public FilesFoldersController getFilesFolders() {
        return FilesFoldersController.getInstance();
    }

    /**
     * Singleton access to Playlists controller
     * @return	Returns the PlaylistsController instance 
     */
    public PlaylistsController getPlaylists() {
        return PlaylistsController.getInstance();
    }

    /**
     * Singleton access to Shares controller
     * @return	Returns the SharesController instance 
     */
    public SharesController getShares() {
        return SharesController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public PersonalCloudStorageAPIsClient() {	
	}

    /**
     * Client initialization constructor 
     */     
    public PersonalCloudStorageAPIsClient(String oAuthAccessToken) {
        this();
        Configuration.oAuthAccessToken = oAuthAccessToken;
    }
}